# Generated by Django 6.1 on 2026-09-05 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAcopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CertificacionAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_certificacion', models.CharField(max_length=100)),
                ('entidad_emisora', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FundoProductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fundo', models.CharField(max_length=100)),
                ('propietario_dni_ruc', models.CharField(max_length=20)),
                ('hectareas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valido_exportacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariedadCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cultivo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoteRecepcionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('toneladas_brutas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('porcentaje_descarte', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_evaluacion', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='agrotrace.fundoproductor')),
            ],
        ),
    ]
