# Generated by Django 6.1.1 on 2026-09-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variedadcultivo',
            old_name='tipo',
            new_name='temporada_cosecha',
        ),
        migrations.RemoveField(
            model_name='certificacionagricola',
            name='nombre_certificacion',
        ),
        migrations.RemoveField(
            model_name='variedadcultivo',
            name='nombre_cultivo',
        ),
        migrations.AddField(
            model_name='centroacopio',
            name='capacidad_toneladas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificacionagricola',
            name='codigo_norma',
            field=models.CharField(default='SIN-DATO', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificacionagricola',
            name='dias_vigencia',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variedadcultivo',
            name='nombre_producto',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variedadcultivo',
            name='temperatura_almacenamiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundoproductor',
            name='propietario_dni_ruc',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='loterecepcionado',
            name='codigo_lote',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='loterecepcionado',
            name='estado_evaluacion',
            field=models.CharField(choices=[('Aprobado Exportacion', 'Aprobado Exportación'), ('Mercado Nacional', 'Mercado Nacional'), ('Rechazado', 'Rechazado')], default='Mercado Nacional', max_length=50),
        ),
    ]
