# Generated by Django 6.1 on 2026-09-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrace', '0002_rename_tipo_variedadcultivo_temporada_cosecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variedadcultivo',
            old_name='temporada_cosecha',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='centroacopio',
            name='capacidad_toneladas',
        ),
        migrations.RemoveField(
            model_name='certificacionagricola',
            name='codigo_norma',
        ),
        migrations.RemoveField(
            model_name='certificacionagricola',
            name='dias_vigencia',
        ),
        migrations.RemoveField(
            model_name='variedadcultivo',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='variedadcultivo',
            name='temperatura_almacenamiento',
        ),
        migrations.AddField(
            model_name='certificacionagricola',
            name='nombre_certificacion',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variedadcultivo',
            name='nombre_cultivo',
            field=models.CharField(default='Sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundoproductor',
            name='propietario_dni_ruc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loterecepcionado',
            name='codigo_lote',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='loterecepcionado',
            name='estado_evaluacion',
            field=models.CharField(max_length=50),
        ),
    ]
