# Generated by Django 6.1 on 2026-09-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrace', '0003_rename_temporada_cosecha_variedadcultivo_tipo_and_more'),
    ]

    operations = [
    ]
